name: Build

on:
  push:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: make format-check

  check-cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: make check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libreadline-dev

      - name: Build
        run: make

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ctable
          path: bin/release/ctable
